const actionTypes = Object.freeze({
  //user
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGOUT: 'USER_LOGOUT',
  //cart
  UPDATE_CART_COUNT: 'UPDATE_CART_COUNT',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
  UPDATE_DETAIL: 'UPDATE_DETAIL',
  MERGE_DETAIL: 'MERGE_DETAIL',
  CLEAR_CART: 'CLEAR_CART',
  SAVE_CART_FOR_CHECKOUT: 'SAVE_CART_FOR_CHECKOUT',
  CLEAR_CHECKOUT_CART: 'CLEAR_CHECKOUT_CART',
  //appointment
  SAVE_APPOINTMENT_CHECKOUT: 'SAVE_APPOINTMENT_CHECKOUT',
  CLEAR_APPOINTMENT_CHECKOUT: 'CLEAR_APPOINTMENT_CHECKOUT',
  SAVE_FUAPPOINTMENT_INFO: 'SAVE_FUAPPOINTMENT_INFO',
  CLEAR_FUAPPOINTMENT_INFO: 'CLEAR_FUAPPOINTMENT_INFO',
  //billtrack
  SAVE_TRACK_INFO: 'SAVE_TRACK_INFO',
  CLEAR_TRACK_INFO: 'CLEAR_TRACK_INFO',
  //preselect
  SAVE_PRESELECT_INFO: 'SAVE_PRESELECT_INFO',
  CLEAR_PRESELECT_INFO: 'CLEAR_PRESELECT_INFO',
  SELECT_SERVICE_TYPE: 'SELECT_SERVICE_TYPE',
  //page notification
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
});
export default actionTypes;