const actionTypes = Object.freeze({
  //user
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGOUT: 'USER_LOGOUT',
  //cart
  UPDATE_CART_COUNT: 'UPDATE_CART_COUNT',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
  UPDATE_DETAIL: 'UPDATE_DETAIL',
  MERGE_DETAIL: 'MERGE_DETAIL',
  CLEAR_CART: 'CLEAR_CART',
  SAVE_CART_FOR_CHECKOUT: 'SAVE_CART_FOR_CHECKOUT',
  CLEAR_CHECKOUT_CART: 'CLEAR_CHECKOUT_CART',
});
export default actionTypes;
